"""Stage 8 -- export: the spreadsheet the user actually works from.

Six tabs in the order a person uses them: Read Me, Call List, Qualification,
Company Profiles, Contacts, All Leads. The Call List is generated by ranking,
not by hand, so it stays correct as the database grows.
"""

from __future__ import annotations

import json
import logging
from datetime import date
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from prospector import config
from prospector.config import load_plan
from prospector.database import get_connection, get_stats

log = logging.getLogger(__name__)

FONT = "Arial"
HDR_FILL = PatternFill("solid", fgColor="1F3864")
HDR_FONT = Font(name=FONT, bold=True, color="FFFFFF", size=10)
BASE = Font(name=FONT, size=10)
BOLD = Font(name=FONT, size=10, bold=True)
SMALL_IT = Font(name=FONT, size=9, italic=True)
TITLE = Font(name=FONT, size=14, bold=True, color="1F3864")
WRAP = Alignment(wrap_text=True, vertical="top")
TOP = Alignment(vertical="top")
THIN = Border(*[Side(style="thin", color="D9D9D9")] * 4)

REL_FILL = {
    "High": PatternFill("solid", fgColor="C6EFCE"),
    "Medium": PatternFill("solid", fgColor="FFEB9C"),
    "Low": PatternFill("solid", fgColor="F2F2F2"),
    "Not relevant": PatternFill("solid", fgColor="FFFFFF"),
}
# Qualification labels are generated per project, so fills are keyed by
# position (best to worst) rather than by text.
LEVEL_FILLS = [
    PatternFill("solid", fgColor="C6EFCE"),
    PatternFill("solid", fgColor="FFEB9C"),
    PatternFill("solid", fgColor="FCE4D6"),
    PatternFill("solid", fgColor="F2F2F2"),
]


def _header(ws, cols, widths, row=1):
    for i, (c, w) in enumerate(zip(cols, widths), 1):
        cell = ws.cell(row=row, column=i, value=c)
        cell.font = HDR_FONT
        cell.fill = HDR_FILL
        cell.alignment = Alignment(wrap_text=True, vertical="center")
        ws.column_dimensions[get_column_letter(i)].width = w
    ws.row_dimensions[row].height = 30
    ws.freeze_panes = ws.cell(row=row + 1, column=1)


def _write(ws, row, values, height=None, bold_first=True):
    for j, v in enumerate(values, 1):
        cell = ws.cell(row=row, column=j, value=v)
        cell.font = BOLD if (bold_first and j == 1) else BASE
        cell.alignment = WRAP
        cell.border = THIN
    if height:
        ws.row_dimensions[row].height = height


def rank_score(row, labels: list[str]) -> int:
    """How high up the call list this lead belongs.

    The qualification score already blends the level with the weighted criteria
    it matched, so this mostly adds relevance and a small bonus for having a
    named contact -- a qualified lead you cannot reach is worth less than one
    you can.
    """
    score = int(row["qualification_score"] or 0)
    score += {"High": 12, "Medium": 6}.get(row["relevance"] or "", 0)
    try:
        if json.loads(row["people_json"] or "[]"):
            score += 5
    except (json.JSONDecodeError, TypeError):
        pass
    return score


def build_workbook(out_path: str | Path | None = None, call_list_size: int = 30) -> Path:
    plan = load_plan()
    title = plan.get("title", "Lead research")
    labels = [lv["label"] for lv in plan.get("qualification_levels", [])]

    rows = get_connection().execute("SELECT * FROM leads").fetchall()
    stats = get_stats()

    if out_path is None:
        slug = config.slugify(title)
        Path(config.EXPORT_DIR).mkdir(parents=True, exist_ok=True)
        out_path = Path(config.EXPORT_DIR) / f"{slug}_leads_{date.today():%Y%m%d}.xlsx"
    out_path = Path(out_path)

    ranked = sorted(rows, key=lambda r: -rank_score(r, labels))
    qualified = [r for r in rows if r["qualification_level"]]

    wb = Workbook()

    # -- Read Me -----------------------------------------------------------
    ws = wb.active
    ws.title = "Read Me"
    ws.column_dimensions["A"].width = 22
    ws.column_dimensions["B"].width = 112

    criteria_text = " | ".join(
        f"{c.get('name')} (weight {c.get('weight', 3)})"
        for c in plan.get("qualification_criteria", [])
    ) or "none defined"

    lines = [
        ("TITLE", f"{title} - lead research"),
        ("You asked for", plan.get("prompt", "")),
        ("Understood as", plan.get("objective", "")),
        ("Ideal lead", plan.get("target_profile", "")),
        ("Regions", ", ".join(plan.get("regions", [])) or "not restricted"),
        ("Qualified on", criteria_text),
        ("Generated", f"{date.today():%d %B %Y} by Prospector"),
        ("", ""),
        ("HOW TO USE", "Start on 'Call List'. 'Qualification' shows the evidence behind "
                       "every rating. 'Contacts' has who to ask for. 'All Leads' is "
                       "everything found, with filters on."),
        ("", ""),
        ("How leads were found", f"{stats['total']} companies came from "
                                 f"{len(plan.get('discovery_queries', []))} web searches "
                                 f"plus anything you uploaded. Each was then researched "
                                 f"against its own website and public sources."),
        ("Ratings", " / ".join(labels) if labels else "not set"),
        ("Evidence", "Ratings are built only from text the researcher was actually "
                     "shown -- the company's own pages and public search results. A top "
                     "rating returned with nothing behind it is downgraded automatically, "
                     "and sources are kept only where they were among the pages read. "
                     "It is still a machine reading marketing copy: spot-check the "
                     "Sources column before quoting a claim in a meeting."),
        ("Contacts", "A name is kept only where it appeared in the pages read. Names "
                     "that could not be found in any source were discarded rather than "
                     "listed, so this tab is shorter than it could be and more reliable "
                     "than it would otherwise be."),
        ("Not publicly available", "Written literally where a company does not publish a "
                                   "figure. No revenue or headcount here is estimated."),
        ("Coverage", f"{stats['total']} leads, {stats['resolved']} websites found, "
                     f"{stats['classified']} classified, {stats['qualified']} qualified, "
                     f"{stats['with_people']} with at least one named contact "
                     f"(searched on {stats.get('people_searched', 0)})."),
        ("", ""),
        ("Worth knowing", "A company with no website was not found confidently rather "
                          "than guessed at -- a wrong site produces false evidence for "
                          "every stage after it. The 'Researched from' column in All Leads "
                          "says whether a company was judged from its own pages or from "
                          "its name alone; treat a name-only row as a lead to check, not "
                          "a finding."),
    ]
    r = 1
    for label, text in lines:
        if label == "TITLE":
            ws.cell(row=r, column=1, value=text).font = TITLE
            r += 2
            continue
        ws.cell(row=r, column=1, value=label).font = BOLD
        ws.cell(row=r, column=1).alignment = TOP
        ws.cell(row=r, column=2, value=text).font = BASE
        ws.cell(row=r, column=2).alignment = WRAP
        ws.row_dimensions[r].height = 15 * (max(len(str(text)), 1) // 108 + 1)
        r += 1

    # -- Call List ---------------------------------------------------------
    ws = wb.create_sheet("Call List")
    _qualified_total = len([r for r in ranked if r["qualification_level"]])
    _banner = ("Ranked by how well each company matches your criteria, "
               "with a bump for having a named contact.")
    if _qualified_total > call_list_size:
        # It silently showed the top 30, so a reader with 200 qualified leads
        # reasonably concluded there were 30.
        _banner += (f"  Showing the top {call_list_size} of {_qualified_total} "
                    f"qualified - the rest are on the Qualification tab.")
    ws.cell(row=1, column=1, value=_banner).font = TITLE
    ws.merge_cells("A1:G1")
    ws.row_dimensions[1].height = 22
    _header(ws, ["Rank", "Company", "What they do", "Rating", "Score",
                 "Why they qualify", "Who to contact"],
            [7, 36, 28, 20, 8, 66, 34], row=3)

    for i, row in enumerate([r for r in ranked if r["qualification_level"]][:call_list_size], 4):
        try:
            people = json.loads(row["people_json"] or "[]")
        except (json.JSONDecodeError, TypeError):
            people = []
        contact = "\n".join(f"{p.get('name')} - {p.get('title')}" for p in people[:3])
        _write(ws, i, [
            i - 3, row["company_name"], row["category"] or "",
            row["qualification_level"] or "", row["qualification_score"] or 0,
            (row["qualification_evidence"] or "").strip()[:600], contact,
        ], height=48)
        ws.cell(row=i, column=1).font = BOLD
        if row["qualification_level"] in labels:
            ws.cell(row=i, column=4).fill = LEVEL_FILLS[labels.index(row["qualification_level"])]
    ws.freeze_panes = "A4"

    # -- Qualification -----------------------------------------------------
    ws = wb.create_sheet("Qualification")
    _header(ws, ["Company", "Website", "What they do", "Type", "Relevance", "Rating",
                 "Score", "Criteria met", "Evidence", "Sources"],
            [34, 26, 26, 22, 12, 20, 8, 28, 74, 46])
    # Levels stored before the plan was edited will not be in `labels`. They used
    # to sort to the bottom, lose their colour, and read as zero in the Summary
    # formulas while the tab below was full -- and editing the plan mid-project
    # is a supported, encouraged workflow.
    order = {label: i for i, label in enumerate(labels)}
    for extra in sorted({r["qualification_level"] for r in qualified
                         if r["qualification_level"] and r["qualification_level"] not in order}):
        order[extra] = len(order)
    qrows = sorted(qualified, key=lambda r: (order.get(r["qualification_level"] or "", 9),
                                             -(r["qualification_score"] or 0)))
    for i, row in enumerate(qrows, 2):
        try:
            sources = ", ".join(json.loads(row["qualification_sources"] or "[]")[:4])
        except (json.JSONDecodeError, TypeError):
            sources = ""
        _write(ws, i, [
            row["company_name"], row["website"] or "", row["products"] or "",
            row["entity_type"] or "", row["relevance"] or "",
            row["qualification_level"] or "", row["qualification_score"] or 0,
            row["qualification_matched"] or "",
            (row["qualification_evidence"] or "").strip(), sources,
        ], height=54)
        if row["qualification_level"] in labels:
            ws.cell(row=i, column=6).fill = LEVEL_FILLS[labels.index(row["qualification_level"])]
    ws.auto_filter.ref = f"A1:J{max(len(qrows) + 1, 2)}"

    # -- Company Profiles --------------------------------------------------
    ws = wb.create_sheet("Company Profiles")
    _header(ws, ["Company", "Website", "Approx annual revenue", "Employees",
                 "Year established", "Public / Private", "Parent company",
                 "Main sites", "Countries / markets"],
            [34, 26, 32, 15, 15, 24, 26, 40, 38])
    profiled = sorted((r for r in rows if r["profiled_at"]),
                      key=lambda r: -rank_score(r, labels))
    for i, row in enumerate(profiled, 2):
        _write(ws, i, [
            row["company_name"], row["website"] or "", row["revenue"] or "",
            row["employees"] or "", row["founded"] or "", row["ownership"] or "",
            row["parent"] or "", row["plants"] or "", row["export_countries"] or "",
        ], height=30)
    ws.auto_filter.ref = f"A1:I{max(len(profiled) + 1, 2)}"

    # -- Contacts ----------------------------------------------------------
    ws = wb.create_sheet("Contacts")
    _header(ws, ["Company", "Rating", "Name", "Position", "Why them", "LinkedIn"],
            [34, 20, 24, 36, 42, 40])
    i = 2
    for row in ranked:
        try:
            people = json.loads(row["people_json"] or "[]")
        except (json.JSONDecodeError, TypeError):
            people = []
        for person in people:
            _write(ws, i, [
                row["company_name"], row["qualification_level"] or "",
                person.get("name", ""), person.get("title", ""),
                person.get("note", ""), person.get("linkedin", ""),
            ], height=24)
            ws.cell(row=i, column=3).font = BOLD
            i += 1
    ws.cell(row=i + 1, column=1,
            value="Companies missing here had no named person in public sources - "
                  "ask the switchboard for the role instead.").font = SMALL_IT
    ws.auto_filter.ref = f"A1:F{max(i - 1, 2)}"

    # -- First Contact -----------------------------------------------------
    drafted = [r for r in ranked if r["outreach_at"]]
    if drafted:
        ws = wb.create_sheet("First Contact")
        ws.cell(row=1, column=1,
                value="Drafts only - nothing has been sent. Send these from your own "
                      "mailbox, a few a day, and reply personally.").font = TITLE
        ws.merge_cells("A1:F1")
        ws.row_dimensions[1].height = 22
        _header(ws, ["Company", "Send to", "Rating", "The hook", "Subject", "Message"],
                [30, 30, 18, 34, 34, 76], row=3)
        for i, row in enumerate(drafted, 4):
            try:
                people = json.loads(row["people_json"] or "[]")
            except (json.JSONDecodeError, TypeError):
                people = []
            send_to = (f"{people[0].get('name')} - {people[0].get('title')}"
                       if people else "no named contact - ask for the role")
            _write(ws, i, [
                row["company_name"], send_to, row["qualification_level"] or "",
                row["outreach_angle"] or "", row["outreach_subject"] or "",
                row["outreach_body"] or "",
            ], height=86)
            if row["qualification_level"] in labels:
                ws.cell(row=i, column=3).fill = LEVEL_FILLS[
                    labels.index(row["qualification_level"])]
        ws.freeze_panes = "A4"

    # -- All Leads ---------------------------------------------------------
    ws = wb.create_sheet("All Leads")
    _header(ws, ["#", "Company", "Website", "Researched from", "Country", "Type",
                 "Category", "What they do", "Relevance", "Rating", "Score",
                 "Found via", "Notes"],
            [5, 36, 26, 18, 16, 22, 22, 50, 13, 20, 8, 30, 26])
    rel_order = {"High": 0, "Medium": 1, "Low": 2, "Not relevant": 3}
    all_rows = sorted(rows, key=lambda r: (
        order.get(r["qualification_level"] or "", 9),
        rel_order.get(r["relevance"] or "", 4),
        (r["company_name"] or "").lower(),
    ))
    for i, row in enumerate(all_rows, 2):
        # How much this row is actually worth. A company judged from its name
        # alone, and one whose site was read end to end, used to be identical
        # here -- and confidence was stored on every row and shown on none.
        if not row["website"]:
            basis = "name only - no site found"
        elif row["from_name_only"]:
            basis = "name only"
        elif (row["website_confidence"] or 0) < 0.5:
            basis = "site (uncertain match)"
        else:
            basis = "its own website"

        _write(ws, i, [
            i - 1, row["company_name"], row["website"] or "", basis,
            row["country"] or "",
            row["entity_type"] or "", row["category"] or "", row["products"] or "",
            row["relevance"] or "unclassified", row["qualification_level"] or "",
            row["qualification_score"] or "", row["discovered_via"] or row["source_list"] or "",
            row["notes"] or "",
        ], bold_first=False)
        fill = REL_FILL.get(row["relevance"] or "")
        if fill:
            ws.cell(row=i, column=9).fill = fill
        if row["qualification_level"] in labels:
            ws.cell(row=i, column=10).fill = LEVEL_FILLS[labels.index(row["qualification_level"])]
    ws.auto_filter.ref = f"A1:M{max(len(all_rows) + 1, 2)}"

    # -- Summary -----------------------------------------------------------
    ws = wb.create_sheet("Summary")
    ws.column_dimensions["A"].width = 42
    ws.column_dimensions["B"].width = 12
    ws.column_dimensions["C"].width = 56
    ws.cell(row=1, column=1, value=f"Summary - {stats['total']} leads").font = TITLE
    _header(ws, ["Breakdown", "Count", "Note"], [42, 12, 56], row=3)

    n = len(all_rows) + 1
    summary = [
        ("Leads found", f"=COUNTA('All Leads'!B2:B{n})", "Everything discovered or uploaded"),
        ("Websites found", stats["resolved"], "Official sites resolved automatically"),
        ("Classified", stats["classified"], "Sorted for relevance to your brief"),
        ("Qualified", stats["qualified"], "Judged against your criteria"),
        ("With named contacts", stats["with_people"], "See the Contacts tab"),
        ("", None, ""),
        ("High relevance", f"=COUNTIF('All Leads'!I2:I{n},\"High\")", "Squarely what you asked for"),
        ("Medium relevance", f"=COUNTIF('All Leads'!I2:I{n},\"Medium\")", "Adjacent, worth a look"),
        ("Low relevance", f"=COUNTIF('All Leads'!I2:I{n},\"Low\")", "Same industry, not the brief"),
        ("Not relevant", f"=COUNTIF('All Leads'!I2:I{n},\"Not relevant\")", "Filtered out"),
        # Without this the four named levels do not add up to "Leads found",
        # and the missing rows have no line of their own to account for them.
        ("Not yet classified", f"=COUNTIF('All Leads'!I2:I{n},\"unclassified\")",
         "Found, but the run stopped before sorting them"),
        ("", None, ""),
    ]
    for i, label in enumerate(labels):
        note = (plan.get("qualification_levels") or [{}] * 4)[i].get("definition", "")[:120]
        summary.append((f"  {label}", f"=COUNTIF('All Leads'!J2:J{n},\"{label}\")", note))

    r = 4
    for label, value, note in summary:
        ws.cell(row=r, column=1, value=label).font = BASE if label.startswith("  ") else BOLD
        if value is not None:
            ws.cell(row=r, column=2, value=value).font = BASE
        ws.cell(row=r, column=3, value=note).font = BASE
        ws.cell(row=r, column=3).alignment = WRAP
        r += 1
    ws.cell(row=r + 1, column=1,
            value="Counts in column B are live formulas over the All Leads tab - "
                  "re-rate a row there and these update.").font = SMALL_IT

    out_path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(out_path)
    log.info("Workbook written: %s", out_path)
    return out_path


def run_export(out_path: str | Path | None = None) -> dict:
    return {"status": "ok", "path": str(build_workbook(out_path))}
