; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
;
; Targets Inno Setup 6.2.x. Directives added in 6.3 and later are avoided on
; purpose -- notably ArchitecturesAllowed=x64compatible, which is a compile
; error on 6.2.2 and fails with a message that does not explain itself.
;
; Compiled by installer\build_installer.ps1, which passes MyAppVersion in.
; To compile by hand:
;   "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer\prospector.iss

#define MyAppName "Prospector"
#define MyAppPublisher "Akshay Kharvi"
#define MyAppURL "https://github.com/Pickle-Pixel/Prospector"
#define MyAppExeName "Prospector.exe"

; Overridden by the build script: /DMyAppVersion=0.2.0
#ifndef MyAppVersion
  #define MyAppVersion "0.2.0"
#endif

; Where PyInstaller left the one-folder build.
#ifndef MySourceDir
  #define MySourceDir "..\dist\Prospector"
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the
; same AppId value in installers for other applications.
AppId={{7A2F1C64-3B5E-4B21-9D0A-5C6E8F1B2D33}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Per-user install: no administrator prompt, no admin account needed. The whole
; point is that a non-technical person can install this on their own.
PrivilegesRequired=lowest
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
OutputDir=..\dist
OutputBaseFilename=ProspectorSetup-{#MyAppVersion}
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
UninstallDisplayName={#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; Upgrading over a running copy silently fails to replace the files that are
; locked, which produces a half-old half-new install that crashes only on
; upgraded machines -- the hardest kind of bug to hear about. Ask instead.
CloseApplications=yes
CloseApplicationsFilter=*.exe,*.dll,*.pyd
RestartApplications=no
; Named so a second copy of the installer, and the app itself, can be detected.
AppMutex=ProspectorSetupMutex

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[InstallDelete]
; PyInstaller renames its private directory between versions, so an upgrade used
; to leave both generations side by side in {app}. The stale one shadows the new
; one on import and the app dies with a missing-module error that only ever
; happens on machines that upgraded.
Type: filesandordirs; Name: "{app}\_internal"
Type: files; Name: "{app}\*.pyd"
Type: files; Name: "{app}\python*.dll"
Type: files; Name: "{app}\base_library.zip"

[Files]
; The wizard normally emits a separate line for the main exe plus a wildcard for
; everything else. With a PyInstaller one-folder build the wildcard already
; covers the exe, and listing it twice compiles it into the setup twice.
Source: "{#MySourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; The user's projects, spreadsheets and downloaded AI model live under
; %USERPROFILE%\.prospector. That folder is deliberately NOT removed here --
; uninstalling the program must never throw away the user's work. Only the
; engine we downloaded goes, since it is re-fetchable and large.
Type: filesandordirs; Name: "{%USERPROFILE}\.prospector\shared\engine"

[Code]
function InitializeSetup(): Boolean;
var
  Version: TWindowsVersion;
begin
  GetWindowsVersionEx(Version);
  { Windows 10 is build 10240. Below that the bundled Python runtime and the
    TLS stack Prospector needs are not dependable. }
  if Version.Major < 10 then
  begin
    MsgBox('Prospector needs Windows 10 or later.', mbCriticalError, MB_OK);
    Result := False;
  end
  else
    Result := True;
end;
